
__default__:
  account: NN9316K
  nodes : 1
  mem : 5G
  time : 00:30:00
  job-name : "{rule}.{wildcards}"
  output : "logs/saga/{rule}.{wildcards}.out"
  error : "logs/saga/{rule}.{wildcards}.err"
  