
__default__:
  account: NN9316K
  nodes : 1
  mem : 5G
  time : 00:30:00
  job-name : "{rule}.{wildcards}"
  output : "logs/saga/{rule}.{wildcards}.out"
  error : "logs/saga/{rule}.{wildcards}.err"
  gres : "localscratch:0G"

makeMovie:
  mem : 8G
  time : 01:00:00

runBrainSim:
  gres : "localscratch:100G"
