
__default__:
  account: NN9279K
  nodes : 1
  mem : 5G
  time : 00:60:00
  job-name : "{rule}.{wildcards}"
  output : "logs/saga/{rule}.{wildcards}.out"
  error : "logs/saga/{rule}.{wildcards}.err"
  gres : "localscratch:0G"

makeMovie:
  mem : 10G
  time : 00:60:00


makeFlowPlots:
  mem : 20G
  time : 02:00:00

runBrainSim:
  gres : "localscratch:150G"
  #qos : devel
