restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
jobs : 10
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60

__default__:
    account: marius # your hpc account
    time: 60 # default time (minutes)
    nodes: 1
    ntasks: 1
    mem: 10GB # default memory

runBrainSim:
    account: marius # your hpc account
    time: 120 # default time (minutes)
    nodes: 1
    ntasks: 20
    mem: 100GB # default memory